# Generated by Django 2.2.8 on 2021-08-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210829_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='slot',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
